<nav>
	<ul>
	  <li><a <?php echo ($page=="index")?"class='active'":"";  ?> href="index.php">Home</a></li>
	  <li><a <?php echo ($page=="enquire")?"class='active'":"";  ?> href="enquire.php">Enquire</a></li>       
	  <li><a <?php echo ($page=="payment")?"class='active'":"";  ?> href="payment.php">Payment</a></li>
	  <li><a <?php echo ($page=="enhancements")?"class='active'":"";  ?> href="enhancements.php">Manager</a></li>
	</ul>
</nav>